# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

development:
  <<: *default
  database: smart_catalog_development

test:
  <<: *default
  database: smart_catalog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
