# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  database: smart_catalog_development
  <% end %>

test:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  database: smart_catalog_test
  <% end %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
